#pragma once

#include "Base.hpp"
#include "include/01.hpp"
#include "include/02.hpp"
#include "include/03.hpp"
#include "include/04.hpp"
#include "include/05.hpp"
#include "include/06.hpp"
#include "include/07.hpp"
#include "include/08.hpp"
// #include "include/09.hpp"
// #include "include/10.hpp"
// #include "include/11.hpp"
// #include "include/12.hpp"
// #include "include/13.hpp"
// #include "include/14.hpp"
// #include "include/15.hpp"
// #include "include/16.hpp"
// #include "include/17.hpp"
// #include "include/18.hpp"
// #include "include/19.hpp"
// #include "include/20.hpp"
// #include "include/21.hpp"
// #include "include/22.hpp"
// #include "include/23.hpp"
// #include "include/24.hpp"
// #include "include/25.hpp"
